services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: movies_app
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: