### Get token
POST http://localhost:5281/token
Content-Type: application/json

{
  "userId": "9dfdebf2-b7b1-4526-9358-850b21eb6aad",
  "email": "anton@azdanov.dev",
  "customClaims": {
    "admin": "true",
    "trusted_member": "false"
  }
}

> {%
    client.global.set("token", response.body);
%}

### Create a movie
POST https://localhost:44392/api/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Dune",
  "yearOfRelease": 2021,
  "genres": [
    "Action",
    "Adventure",
    "Drama"
  ]
}

> {%
    client.global.set("dune_movie_id", response.body.id);
    client.global.set("dune_slug", response.body.slug);
%}

### Get a movie
GET https://localhost:44392/api/movies/{{dune_movie_id}}
Authorization: Bearer {{token}}

### Get a movie by slug
GET https://localhost:44392/api/movies/{{dune_slug}}
Authorization: Bearer {{token}}


### Get another movie
GET https://localhost:44392/api/movies/toy-story-1995
Authorization: Bearer {{token}}

### Get another movie by id
GET https://localhost:44392/api/movies/ad379b9b-257e-445c-a9ea-10da301f2386
Authorization: Bearer {{token}}

### Get another movie by id (deprecated, slow)
GET https://localhost:44392/api/movies/ad379b9b-257e-445c-a9ea-10da301f2386?api-version=1.0
Authorization: Bearer {{token}}

### Get all movies filtered
GET https://localhost:44392/api/movies?yearOfRelease=2000
Authorization: Bearer {{token}}

### Get all movies sorted
GET https://localhost:44392/api/movies?sortBy=title
Authorization: Bearer {{token}}

### Get all movies paginated
GET https://localhost:44392/api/movies?page=1&pageSize=10
Authorization: Bearer {{token}}


### Update a movie
PUT https://localhost:44392/api/movies/{{dune_movie_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Dune",
  "yearOfRelease": 1984,
  "genres": [
    "Action",
    "Adventure",
    "Sci-Fi"
  ]
}


### Delete a movie
DELETE https://localhost:44392/api/movies/{{dune_movie_id}}
Authorization: Bearer {{token}}

### Rate a movie
PUT https://localhost:44392/api/movies/{{dune_movie_id}}/ratings
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "rating": 5
}

### Delete a rating
DELETE https://localhost:44392/api/movies/{{dune_movie_id}}/ratings
Authorization: Bearer {{token}}

### Get my ratings
GET https://localhost:44392/api/ratings/me
Authorization: Bearer {{token}}
