### Create a movie
POST https://localhost:44392/api/movies
Content-Type: application/json

{
  "title": "Dune",
  "yearOfRelease": 2021,
  "genres": [
    "Action",
    "Adventure",
    "Drama"
  ]
}

> {%
    client.global.set("created_movie_id", response.body.id);
%}

### Get a movie
GET https://localhost:44392/api/movies/{{created_movie_id}}

### Get all movies
GET https://localhost:44392/api/movies