### Get token
POST http://localhost:5281/token
Content-Type: application/json

{
  "userId": "6645F217-1B5F-41A7-B158-9448C911B448",
  "email": "anton@azdanov.dev",
  "customClaims": {
    "role": "admin",
    "trusted_member": "true"
  }
}

> {%
    client.global.set("token", response.body);
%}

### Create a movie
POST https://localhost:44392/api/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Dune",
  "yearOfRelease": 2021,
  "genres": [
    "Action",
    "Adventure",
    "Drama"
  ]
}

> {%
    client.global.set("dune_movie_id", response.body.id);
    client.global.set("dune_slug", response.body.slug);
%}

### Get a movie
GET https://localhost:44392/api/movies/{{dune_movie_id}}

### Get a movie by slug
GET https://localhost:44392/api/movies/{{dune_slug}}


### Create another movie
POST https://localhost:44392/api/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Interstellar",
  "yearOfRelease": 2014,
  "genres": [
    "Adventure",
    "Drama",
    "Sci-Fi"
  ]
}

> {%
    client.global.set("interstellar_movie_id", response.body.id);
    client.global.set("interstellar_slug", response.body.slug);
%}

### Get another movie
GET https://localhost:44392/api/movies/{{interstellar_movie_id}}

### Get another movie by slug
GET https://localhost:44392/api/movies/{{interstellar_slug}}


### Get all movies
GET https://localhost:44392/api/movies


### Update a movie
PUT https://localhost:44392/api/movies/{{dune_movie_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Dune",
  "yearOfRelease": 1984,
  "genres": [
    "Action",
    "Adventure",
    "Sci-Fi"
  ]
}


### Delete a movie
DELETE https://localhost:44392/api/movies/{{dune_movie_id}}
Authorization: Bearer {{token}}

### Delete another movie
DELETE https://localhost:44392/api/movies/{{interstellar_movie_id}}
Authorization: Bearer {{token}}